version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: jobtracker-backend-dev
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/jobtracker
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: jobtracker-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: jobtracker
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
