# Dockerfile.dev

FROM python:3.12-slim

# Set workdir
WORKDIR /app

# Install Poetry
RUN pip install --no-cache-dir poetry

# Copy dependencies
COPY pyproject.toml poetry.lock* ./

# Install dependencies (dev included)
RUN poetry config virtualenvs.create false && poetry install --no-interaction --no-root


# Copy source code
COPY . .

# Expose port
EXPOSE 8000

# Run with live reload
CMD ["poetry", "run", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
